[package]
name = "rop-gadget-finder"
version = "1.0.0-dev.1"
edition = "2021"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
log = "0.4.17"
colored = "2.0.0"
simple_logger = "4.1.0"
thiserror = "1.0.40"

goblin = "0.6.1"
capstone = "0.11.0"
regex = "1.8.1"